export const FETCH_OKRS = "FETCH_OKRS";
export const OKRS_RECEIVED = "OKRS_RECEIVED";
export const FILTER_OKRS = "FILTER_OKRS";
export const ERROR_OCCURRED = "ERROR_OCCURRED";
export const FETCHING_DATA = "FETCHING_DATA";
export const FETCH_COMPLETE = "FETCH_COMPLETE";